# Generated by Django 6.0.3 on 2026-03-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buymodel',
            old_name='user',
            new_name='client',
        ),
        migrations.AlterField(
            model_name='buymodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preço unitário'),
        ),
    ]
